<?php
require_once "conexion.php";

class ModeloAnalLaboratorio
{
    /*=============================================
    --- RENDER COMPROBANTE PDF
    =============================================*/
    public function viewLoadAnalLaboratorio($tipo_comprobante)
    {

        if ($tipo_comprobante == 'sianal') {
            # code...
            $stmt = Conexion::conectar()->query("SELECT * FROM FCH_CONTROL_DE_CALIDAD order by correlativo desc");
        } else {
            $stmt = Conexion::conectar()->query("SELECT * FROM FCH_CONTROL_DE_CALIDAD WHERE tipoanal='$tipo_comprobante' order by correlativo desc");
        }
        # code...

        $listPags["items"] = array();
        foreach ($stmt as $row) {
            $retorn = array(
                "id"                       => $row["id"],
                "letra_tipo_codelabo"      => $row["letra_tipo_codelabo"],
                "correlativo"              => $row["correlativo"],
                "idcodrbpm1"               => $row["idcodrbpm1"],
                "url_img_para_basededatos" => $row["url_img_para_basededatos"],
                "fecha"                    => $row["fecha"],
                "doc_identidad"            => $row["doc_identidad"],
                "nombrecliente"            => $row["nombrecliente"],
                "quienrecibe"              => $row["quienrecibe"],
                "cafe"                     => $row["cafe"],
                "materiaextrana"           => $row["materiaextrana"],
                "procedencia"              => $row["procedencia"],
                "idTipCaf"                 => $row["idTipCaf"],
                "placavehiculo"            => $row["placavehiculo"],
                "altitud"                  => $row["altitud"],
                "fechaentrega"             => $row["fechaentrega"],
                "temperatura"              => $row["temperatura"],
                "humedad"                  => $row["humedad"],
                "observaciones"            => $row["observaciones"],
                "motivorechazo"            => $row["motivorechazo"],
                "rechazo"                  => $row["rechazo"],
                "idfechaentrega"           => $row["idfechaentrega"],
                "obsfinales"               => $row["obsfinales"],
                "tipoanal"                 => $row["tipoanal"],
                "samplenumero"             => $row["samplenumero"],
                "fragrance"                => $row["fragrance"],
                "flavor"                   => $row["flavor"],
                "acidity"                  => $row["acidity"],
                "sweetness"                => $row["sweetness"],
                "body"                     => $row["body"],
                "clean"                    => $row["clean"],
                "overall"                  => $row["overall"],
                "otal"                     => $row["otal"],
                "aftertaste"               => $row["aftertaste"],
                "balance"                  => $row["balance"],
                "uniformity"               => $row["uniformity"],
                "unoextra"                 => $row["unoextra"],
                "dosextra"                 => $row["dosextra"],
                "tresextra"                => $row["tresextra"],
                "notes"                    => $row["notes"],
                "finalscore"               => $row["finalscore"],
                "varidad"                  => $row["varidad"],
                "cosecha"                  => $row["cosecha"],
                "analisis_de_pergamino"    => $row["analisis_de_pergamino"],
                "proceso_organico"         => $row["proceso_organico"],
                "proceso_convencional"     => $row["proceso_convencional"],
                "peso_perg"                => $row["peso_perg"],
                "h_perg"                   => $row["h_perg"],
                "color_perg"               => $row["color_perg"],
                "olor_perg"                => $row["olor_perg"],
                "normal_perg"              => $row["normal_perg"],
                "fresco_perg"              => $row["fresco_perg"],
                "disparejo_perg"           => $row["disparejo_perg"],
                "viejo_perg"               => $row["viejo_perg"],
                "fermento_perg"            => $row["fermento_perg"],
                "negruzco_perg"            => $row["negruzco_perg"],
                "terroso_perg"             => $row["terroso_perg"],
                "otros_perg"               => $row["otros_perg"],
                "hierbas_perg"             => $row["hierbas_perg"],
                "moho_perg"                => $row["moho_perg"],
                "manchado_perg"            => $row["manchado_perg"],
                "peso_oro"                 => $row["peso_oro"],
                "h_oro"                    => $row["h_oro"],
                "color_oro"                => $row["color_oro"],
                "olor_oro"                 => $row["olor_oro"],
                "normal_oro"               => $row["normal_oro"],
                "fresco_oro"               => $row["fresco_oro"],
                "azulado_oro"              => $row["azulado_oro"],
                "viejo_oro"                => $row["viejo_oro"],
                "disparejo_oro"            => $row["disparejo_oro"],
                "fermento_oro"             => $row["fermento_oro"],
                "amarillo_oro"             => $row["amarillo_oro"],
                "terroso_oro"              => $row["terroso_oro"],
                "traslucido_oro"           => $row["traslucido_oro"],
                "hierbas_oro"              => $row["hierbas_oro"],
                "moho_oro"                 => $row["moho_oro"],
                "blanqueado_oro"           => $row["blanqueado_oro"],
                "tbl2_observ"              => $row["tbl2_observ"],
                "tbl2_peso"                => $row["tbl2_peso"],
                "tbl2_porcentaj"           => $row["tbl2_porcentaj"],
                "tbl2_pesouno"             => $row["tbl2_pesouno"],
                "tbl2_porce_uno"           => $row["tbl2_porce_uno"],
                "tbl2_pesodos"             => $row["tbl2_pesodos"],
                "tbl2_porce_dos"           => $row["tbl2_porce_dos"],
                "tbl2_pesotres"            => $row["tbl2_pesotres"],
                "tbl2_porce_tres"          => $row["tbl2_porce_tres"],
                "tbl2_pesocuatro"          => $row["tbl2_pesocuatro"],
                "tbl2_porce_cuatro"        => $row["tbl2_porce_cuatro"],
                "tbl2_pesocinco"           => $row["tbl2_pesocinco"],
                "tbl2_porce_cinco"         => $row["tbl2_porce_cinco"],
                "tbl2_pesoseis"            => $row["tbl2_pesoseis"],
                "tbl2_porce_seis"          => $row["tbl2_porce_seis"],
                "tbl2_pesosiete"           => $row["tbl2_pesosiete"],
                "tbl2_porce_siete"         => $row["tbl2_porce_siete"],
                "total_granu"              => $row["total_granu"],
                "porce_granu"              => $row["porce_granu"],
                "exp_granonegro"           => $row["exp_granonegro"],
                "exp_a"                    => $row["exp_a"],
                "exp_granoagrio"           => $row["exp_granoagrio"],
                "exp_b"                    => $row["exp_b"],
                "exp_cerezaseca"           => $row["exp_cerezaseca"],
                "exp_c"                    => $row["exp_c"],
                "exp_danohongo"            => $row["exp_danohongo"],
                "exp_d"                    => $row["exp_d"],
                "exp_materiaetrana"        => $row["exp_materiaetrana"],
                "exp_e"                    => $row["exp_e"],
                "exp_brocadosevero"        => $row["exp_brocadosevero"],
                "exp_f"                    => $row["exp_f"],
                "exp_parcialnegro"         => $row["exp_parcialnegro"],
                "exp_g"                    => $row["exp_g"],
                "exp_parcialagrio"         => $row["exp_parcialagrio"],
                "exp_h"                    => $row["exp_h"],
                "exp_pergamino"            => $row["exp_pergamino"],
                "exp_i"                    => $row["exp_i"],
                "exp_flotblan"             => $row["exp_flotblan"],
                "exp_j"                    => $row["exp_j"],
                "exp_inmaduro"             => $row["exp_inmaduro"],
                "exp_k"                    => $row["exp_k"],
                "exp_averana"              => $row["exp_averana"],
                "exp_l"                    => $row["exp_l"],
                "exp_conchas"              => $row["exp_conchas"],
                "exp_m"                    => $row["exp_m"],
                "exp_partmord"             => $row["exp_partmord"],
                "exp_n"                    => $row["exp_n"],
                "exp_cascara"              => $row["exp_cascara"],
                "exp_o"                    => $row["exp_o"],
                "exp_brocadoleve"          => $row["exp_brocadoleve"],
                "exp_p"                    => $row["exp_p"],
                "total_rata_expo"          => $row["total_rata_expo"],
                "i50pesodeftotal"          => $row["i50pesodeftotal"],
                "i51pordeftotal"           => $row["i51pordeftotal"],
                "totl_rendimiento_export"  => $row["totl_rendimiento_export"],
                "fecha_create_registro"    => $row["fecha_create_registro"],
                "estado"                   => $row["estado"],
            );
            array_push($listPags["items"], $retorn);
        }
        return json_encode($listPags["items"]);

    }

}
